### PR TITLE
Data bank

### PR DESCRIPTION
**Pull request by omsoo**
Completed the page requirement for the data storage and added the below interactions:

1. When the user changes the content of any input field, the data is saved to the local storage.

2. When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.
You should use the following data model:

3. Created a single JavaScript object with all the data from the entire form and save it in local storage and did not create one local storage entry per input field.

4. Ensured the content of the email field takes only lower case values and check when the user submits the form.

- Also ensured the below conditions were met

5. If the validation is OK, the form is sent.

6.  Checked for linters error

7. Documented the work in a professional way

8. Ensured correct GitHub flow

### CODE REVIEW

**Comment by omsoo** [comment]
Hi,

We just have ONE slot left for the review of the exercise - data storage and have completed and reviewed all the requirements needed for the completion.

Kindly approve for us to proceed,

Regards

**Comment by omsoo** [comment]
Below is the output

image

**Review by Cathella — APPROVED** [review]
## 🔥 Status: Approved 🟢

### Hi @omsoo 👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omsoo** [comment]
Great!

Many thanks
@Hadi111jafari , please take note

**Pull request merged**
